variables:
  SCHEDULER_PARAMETERS: "-pgeneral -t 4:00:00 -N 1 --ntasks-per-node=16"
  GIT_STRATEGY: clone
  NPROCS: 4

stages:
  - build

build:gnu:
  stage: build
  tags: [darwin-slurm-shared]
  script:
    - module load gcc
    - GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:open-mpi/ompi.git
    - pushd ompi
    - rm .gitmodules
    - cp $GITSUBMODULEPATCH .gitmodules
    - git submodule update --init --recursive
    - ./autogen.pl
    - ./configure --with-ucx=no --prefix=$PWD/install_for_mpir
    - make -j 8 install
    - export PATH=$PWD/install_for_mpi/bin:$PATH
    - popd
    - ./autogen.sh
    - ./configure --prefix=$PWD/install/mpir-shim --with-pmix=$PWD/ompi/install_for_mpir
    - export PATH=$PWD/install/mpir-shim/bin:$PATH
    - pushd test/ci
    - ./build.sh
    - ./run.sh
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - ompi/install_for_mpir
      - install/mpir-shim
      - test/ci
    expire_in: 1 week


